# For a detailed guide to building and testing on iOS, read the docs:
# https://circleci.com/docs/2.0/testing-ios/

# Specify the config version - version 2.1 is latest.
version: 2.1

orbs:

  test: circleci/welcome-orb@0.4.1

workflows:

  circleci_test:

    jobs:
      - test/run
