# For a detailed guide to building and testing on iOS, read the docs:
# https://circleci.com/docs/2.0/testing-ios/

# Specify the config version - version 2.1 is latest.
version: 2.1

jobs:
  build-and-test:
        working_directory: ~/circleci/CircleCITest
        macos:
          xcode: 11.3.0
        
        environment:
          DT_VERSION_NUMBER: "1.0"
          DT_BUILD_NUMBER: "1"
      

        steps:
        
        - checkout:
            path: ~/circleci/CircleCITest      
              
              
workflows:
  build-test:
    jobs:
    - build-and-test:
        filters:
          branches:
            only:
               - master
