# For a detailed guide to building and testing on iOS, read the docs:
# https://circleci.com/docs/2.0/testing-ios/

# Specify the config version - version 2.1 is latest.
version: 2.1

jobs:
  test:
    working_directory: ~/circleci/CircleCITest
    macos: 
      xcode: 11.3.0
    steps:
      - checkout:
          path: ../circleci

      - run:
            name: Install CocoaPods
            command: | 
                pod install
      - run:
            name: Build Application
            command: |
                cd ~/circleci/  

workflows:
  circleci_test:
    jobs:
      - test:
          filters:
             branches:
               only:
                   - master  
